on: [push, workflow_dispatch]
name: azure deploy 
env:
  AZURE_LOCATION: norwayeast
  AZURE_PREFIX: ystrte
  AZURE_RESOURCE_GROUP: rg-main
  AZURE_DNS_ZONE: qbits.no
  AZURE_SUBSCRIPTION_ID: a83145a3-215b-44a4-9387-a540faaa58e9

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main

    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.QBITS_AZURE_CREDENTIALS }}

      # Deploy resources
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 'latest'
        inlineScript: |
          
          chmod +x azure/deployAks.sh
          azure/deployAks.sh
