on: [push, workflow_dispatch]
name: azure aks 
env:
  AZURE_LOCATION: norwayeast
  AZURE_PREFIX: ystrte
  AZURE_RESOURCE_GROUP: rg-main
  AZURE_DNS_ZONE: qbits.no
  AZURE_SUBSCRIPTION_ID: a83145a3-215b-44a4-9387-a540faaa58e9
  AZURE_AKS_RG_GREEN: rg-aks-green
  AZURE_AKS_NAME_GREEN: aks-qbits-green
  AZURE_AKS_SUBNET_GREEN: subnet-aks-green
  AZURE_AKS_DNS_PREFIX: aks-qbits-green
  AZURE_AKS_RESOURCE_GROUP: rg-aks
  AZURE_VNET_RESOURCE_GROUP: rg-main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main

    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.QBITS_AZURE_CREDENTIALS }}
    
    - uses: sergeysova/jq-action@v2
    
      # Deploy VNET 
    - name: deploy VNET
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_VNET_RESOURCE_GROUP }}
        template: ./azure/vnet/vnet.bicep
        failOnStdErr: false

      # Deploy AKS 
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 'latest'
        inlineScript: |
          chmod +x azure/aks/deployAks.sh
          azure/aks/deployAks.sh \
            {{ env.AZURE_AKS_RG_GREEN }} \
            {{ env.AZURE_AKS_NAME_GREEN }} \
            {{ env.AZURE_AKS_SUBNET_GREEN }} \
            {{ env.AZURE_AKS_DNS_PREFIX }} 

    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.QBITS_AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.AZURE_AKS_NAME_GREEN }}
        resource-group: ${{ env.AZURE_AKS_RG_GREEN }}

    - run: |
        kubectl apply -k $GITHUB_WORKSPACE/gitops/argocd/git-generator-directory/cluster-addons/argocd
        kubectl apply -f $GITHUB_WORKSPACE/gitops/argocd/git-generator-directory/git-directories.yaml
