on: [push]

name: Azure Kubernetes Deployment

env:
  AZURE_LOCATION: norwayeast
  AZURE_RESOURCE_GROUP: qbits-github

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.QBITS_AZURE_CREDENTIALS }}

      # Create resource group
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.26.1
        inlineScript: |
          az group create -l ${{ env.AZURE_LOCATION }} -n ${{ env.AZURE_RESOURCE_GROUP }}
          az deployment group create \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --template-file ./kubernetes/aks/azuredeploy.bicep \
            --parameters storagePrefix=qbits